// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pos_library;

#nullable disable

namespace pos_library.Migrations
{
    [DbContext(typeof(DatabaseCtx))]
    partial class DatabaseCtxModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("pos_library.models.Customers", b =>
                {
                    b.Property<int>("customer_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("customer_id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("pos_library.models.Employee", b =>
                {
                    b.Property<int>("employee_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("employee_id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("pos_library.models.Inventory", b =>
                {
                    b.Property<int>("inventory_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("inventory_id");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("pos_library.models.Product", b =>
                {
                    b.Property<int>("product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("product_id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("pos_library.models.Sale", b =>
                {
                    b.Property<int>("sale_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("sale_id");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("pos_library.models.SaleDetail", b =>
                {
                    b.Property<int>("sales_detail_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("sales_detail_id");

                    b.ToTable("SaleDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
